### ISSUE TITLE
Automatic imploding of strings?

### ISSUE THREAD

**Issue by Cottser** [jenter/twig-snippets#2]
Thanks for making this :)

Are you sure about this one, and where did you see this? Render arrays are special cased but I think (as one of the D8 theme system maintainers) that's it.

```# implode array of strings, done automatically in D8 twig 
{{ myarray }}```

**Comment by jenter** [comment]
@Cottser I will locate where the documentation noted this & will test the cases today

**Comment by jenter** [comment]
@Cottser the reference I had seen was: https://www.drupal.org/node/1918824 

Another aspect of this example is that one expects all three example to produce the same output, but it doesn't (by default). Take this example:
<?php
  {% set numbers = [{'#markup': 'One'}, {'#markup':'Two'}, {'#markup':'Three'}] %}
  {{ numbers }}
?>

- - - - - - - - - - - - - - - - - - 

I am updating my master branch code to a more correct explanation.

**Comment by jenter** [comment]
Clarified under https://github.com/jenter/twig-snippets#functions--filters

**Comment by Cottser** [comment]
Thanks, that makes more sense. I updated the documentation on drupal.org.

**Comment by jenter** [comment]
Thanks again Scott, let me know if you need any assistance with future documentation, testing, etc in the future. 

@Cottser
